### ISSUE TITLE
Error calling GetApi method

### ISSUE THREAD

**Issue by Pathoschild** [drbirbdev/StardewValley#4]
This mod throws an error when the game starts (see [example log](https://smapi.io/log/2610d2c8dabe4358b7fcbcd2b3be8514)):

```
[GameboyArcade] This mod failed in the GameLoop.GameLaunched event. Technical details:
System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.DefaultBinder.FindMostDerivedNewSlotMeth(MethodBase[] match, Int32 cMatches)
   at System.RuntimeType.GetMethodImplCommon(String name, Int32 genericParameterCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at BirbShared.Mod.ModClassParser.<>c__DisplayClass0_2.<ParseMod>b__1(Object sender, GameLaunchedEventArgs e) in C:\Users\russe\source\repos\StardewValley\BirbShared\Mod\ModClassParser.cs:line 37
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 111
```

The mod calls `mod.Helper.ModRegistry.GetType().GetMethod("GetApi")`, but there are two versions of that method:
```cs
public object? GetApi(string uniqueID);
public TInterface? GetApi<TInterface>(string uniqueID) where TInterface : class;
```

You'll need to specify which one you need to avoid the error. For example:
```cs
mod.Helper.ModRegistry.GetType().GetMethod"GetApi", genericParameterCount: 1, new[] { typeof(string) })
```

**Comment by drbirbdev** [comment]
I think this is fixed now, since the ModClassParser code looks like your example pretty much and I'm not seeing these errors.

I must have released the GameboyArcade using this parser earlier than the parser for some reason.
